grafana:
  adminPassword: "admin123"
  persistence:
    enabled: true
    storageClassName: nfs-client
    size: 5Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.homelab.local

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-client
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.homelab.local

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-client
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false
